service: zenvia-proxy

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
  httpApi:
    cors:
      allowCredentials: false
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedOrigins:
        - '*'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  zenviaProxy:
    handler: index.handler
    events:
      - httpApi:
          path: /send-sms
          method: post
      - httpApi:
          path: /health
          method: get

package:
  patterns:
    - '!node_modules/.cache/**'
    - '!.git/**'
    - '!.serverless/**'
    - '!README.md'
    - '!.gitignore'

# plugins:
#   - serverless-offline

# custom:
#   serverless-offline:
#     httpPort: 3000
#     host: 0.0.0.0

resources:
  Resources:
    # CloudWatch Log Group
    ZenviaProxyLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-zenviaProxy
        RetentionInDays: 14

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: HttpApi
      Export:
        Name: ${self:service}-${self:provider.stage}-restApiId